name: iOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'react-native-nitro-player/ios/**'
      - 'example/ios/**'
      - 'bun.lock'
      - '**/Podfile'
      - '**/Podfile.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
           bun install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install CocoaPods
        working-directory: example/ios
        run: |
          bundle install
          RCT_USE_RN_DEP=1 RCT_USE_PREBUILT_RNCORE=1 bundle exec pod install

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Build iOS
        working-directory: example/ios
        run: |
          xcodebuild build \
            -workspace example.xcworkspace \
            -scheme example \
            -sdk iphonesimulator

